### PR TITLE
Perform CI over Erlang 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I'm trying something out (caching for lolspeed). Don't merge yet. Moving to draft...

**Comment by paulo-ferraz-oliveira** [comment]
`make version` went down from 1m 22s to 7s using cache. 🎉

**Comment by paulo-ferraz-oliveira** [comment]
CI duration went down from 2m 14s to 37s using cache. 🎉

**Review by g-andrade — APPROVED** [review]

**Comment by g-andrade** [comment]
I'm a bit conflicted about dropping CI for OTP 21 while nominally still supporting it (since `minimum_otp_vsn` wasn't bumped.)

**Comment by paulo-ferraz-oliveira** [comment]
We can't support OTP 21 **and** use the latest `rebar3`. You may choose, at a later date, to bump the minimum OTP version, via `rebar3.config`, but this has/should be consistent with changes to other lib.s in a broader scope process.

**Comment by g-andrade** [comment]
> We can't support OTP 21 and use the latest rebar3

We can't? That's fun 🙃

**Pull request merged**
